"""remove_fee_receipt_add_guardian_fields

Revision ID: 01a17874f95b
Revises: 0d2a8e9513d8
Create Date: 2026-05-24 02:50:50.948659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a17874f95b'
down_revision: Union[str, None] = '0d2a8e9513d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('guardian_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('guardian_phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('guardian_relation', sa.String(length=50), nullable=True))
    op.drop_column('students', 'fee_receipt_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fee_receipt_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('students', 'guardian_relation')
    op.drop_column('students', 'guardian_phone')
    op.drop_column('students', 'guardian_name')
    # ### end Alembic commands ###
