"""initial schema

Revision ID: 0d2a8e9513d8
Revises: 
Create Date: 2026-04-22 23:06:34.911184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2a8e9513d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CHIEF_WARDEN', 'ASST_CHIEF_WARDEN', 'WARDEN', 'ASST_WARDEN', 'CARETAKER', 'GUARD', 'STUDENT', 'GUARDIAN', name='role'), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('sent_by', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'IMPORTANT', 'MESS', 'HOLIDAY', 'EVENT', name='broadcastcategory'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mess_menus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('breakfast', sa.String(length=500), nullable=True),
    sa.Column('lunch', sa.String(length=500), nullable=True),
    sa.Column('snacks', sa.String(length=500), nullable=True),
    sa.Column('dinner', sa.String(length=500), nullable=True),
    sa.Column('posted_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('posted_by', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'IMPORTANT', 'MESS', 'HOLIDAY', 'EVENT', name='broadcastcategory'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('caretaker_id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('shift_type', sa.Enum('MORNING', 'EVENING', 'NIGHT', name='shifttype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('handover_note', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caretaker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('roll_number', sa.String(length=100), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('guardian_user_id', sa.Uuid(), nullable=True),
    sa.Column('enrollment_status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'CHECKED_OUT', name='enrollmentstatus'), nullable=False),
    sa.Column('fee_receipt_url', sa.String(length=500), nullable=True),
    sa.Column('permanent_checkout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_status', sa.Enum('IN', 'OUT', name='studentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'STAFF_BEHAVIOR', 'SECURITY', 'ENVIRONMENT', 'RAGGING', 'OTHER', name='complaintcategory'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'ACCEPTED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'ESCALATED', 'REOPENED', name='complaintstatus'), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('escalated_to', sa.Uuid(), nullable=True),
    sa.Column('resolution_note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type', sa.Enum('HOME', 'MEDICAL', 'PERSONAL', 'ACADEMIC', name='leavetype'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'GUARDIAN_CONTACTED', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('caretaker_id', sa.Uuid(), nullable=True),
    sa.Column('caretaker_note', sa.String(length=500), nullable=True),
    sa.Column('guardian_confirmed', sa.Boolean(), nullable=False),
    sa.Column('guardian_note', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['caretaker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('ELECTRICAL', 'PLUMBING', 'FURNITURE', 'INTERNET', 'CLEANLINESS', 'OTHER', name='maintenancecategory'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'ASSIGNED', 'SCHEDULED', 'IN_PROGRESS', 'FIXED', name='maintenancestatus'), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fixed_note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mess_offs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('OUT', 'IN', 'MANUAL', name='movementtype'), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('expected_return', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_return', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guard_id', sa.Uuid(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('movement_type', sa.Enum('OUT', 'IN', 'MANUAL', name='movementtype'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sos_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('TRIGGERED', 'RESPONDED', name='sosstatus'), nullable=False),
    sa.Column('responded_by', sa.Uuid(), nullable=True),
    sa.Column('response_note', sa.String(length=1000), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('visitor_name', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('visitor_phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_duration_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'INSIDE', 'EXITED', name='visitorstatus'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('guard_entry_id', sa.Uuid(), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guard_entry_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_updates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.Enum('SUBMITTED', 'ACCEPTED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'ESCALATED', 'REOPENED', name='complaintstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('SUBMITTED', 'ACCEPTED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'ESCALATED', 'REOPENED', name='complaintstatus'), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint_updates')
    op.drop_table('visitors')
    op.drop_table('sos_alerts')
    op.drop_table('otp_tokens')
    op.drop_table('movement_logs')
    op.drop_table('mess_offs')
    op.drop_table('maintenance_requests')
    op.drop_table('leave_applications')
    op.drop_table('complaints')
    op.drop_table('students')
    op.drop_table('shifts')
    op.drop_table('notices')
    op.drop_table('mess_menus')
    op.drop_table('broadcasts')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('hostels')
    op.drop_table('institutions')
    # ### end Alembic commands ###
