import 'package:freezed_annotation/freezed_annotation.dart';

part 'mess.freezed.dart';
part 'mess.g.dart';

@freezed
class MessMenu with _$MessMenu {
  const factory MessMenu({
    required String id,
    required String hostelId,
    required String date,
    String? breakfast,
    String? lunch,
    String? snacks,
    String? dinner,
    String? postedByName,
    DateTime? createdAt,
  }) = _MessMenu;

  factory MessMenu.fromJson(Map<String, dynamic> json) =>
      _$MessMenuFromJson(json);
}

@freezed
class MessOff with _$MessOff {
  const factory MessOff({
    required String id,
    required String studentId,
    required DateTime fromDate,
    required DateTime toDate,
    String? reason,
    @Default(false) bool isApproved,
    bool? isAutoGenerated,
    DateTime? createdAt,
  }) = _MessOff;

  factory MessOff.fromJson(Map<String, dynamic> json) =>
      _$MessOffFromJson(json);
}
