// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'mess.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$MessMenuImpl _$$MessMenuImplFromJson(Map<String, dynamic> json) =>
    _$MessMenuImpl(
      id: json['id'] as String,
      hostelId: json['hostelId'] as String,
      date: json['date'] as String,
      breakfast: json['breakfast'] as String?,
      lunch: json['lunch'] as String?,
      snacks: json['snacks'] as String?,
      dinner: json['dinner'] as String?,
      postedByName: json['postedByName'] as String?,
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
    );

Map<String, dynamic> _$$MessMenuImplToJson(_$MessMenuImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'hostelId': instance.hostelId,
      'date': instance.date,
      'breakfast': instance.breakfast,
      'lunch': instance.lunch,
      'snacks': instance.snacks,
      'dinner': instance.dinner,
      'postedByName': instance.postedByName,
      'createdAt': instance.createdAt?.toIso8601String(),
    };

_$MessOffImpl _$$MessOffImplFromJson(Map<String, dynamic> json) =>
    _$MessOffImpl(
      id: json['id'] as String,
      studentId: json['studentId'] as String,
      fromDate: DateTime.parse(json['fromDate'] as String),
      toDate: DateTime.parse(json['toDate'] as String),
      reason: json['reason'] as String?,
      isApproved: json['isApproved'] as bool? ?? false,
      isAutoGenerated: json['isAutoGenerated'] as bool?,
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
    );

Map<String, dynamic> _$$MessOffImplToJson(_$MessOffImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'studentId': instance.studentId,
      'fromDate': instance.fromDate.toIso8601String(),
      'toDate': instance.toDate.toIso8601String(),
      'reason': instance.reason,
      'isApproved': instance.isApproved,
      'isAutoGenerated': instance.isAutoGenerated,
      'createdAt': instance.createdAt?.toIso8601String(),
    };
