// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'mess.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$MessMenuImpl _$$MessMenuImplFromJson(Map<String, dynamic> json) =>
    _$MessMenuImpl(
      id: json['id'] as String,
      hostelId: json['hostel_id'] as String,
      date: json['date'] as String,
      breakfast: json['breakfast'] as String?,
      lunch: json['lunch'] as String?,
      snacks: json['snacks'] as String?,
      dinner: json['dinner'] as String?,
      postedByName: json['posted_by_name'] as String?,
      createdAt: json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
    );

Map<String, dynamic> _$$MessMenuImplToJson(_$MessMenuImpl instance) {
  final val = <String, dynamic>{
    'id': instance.id,
    'hostel_id': instance.hostelId,
    'date': instance.date,
  };

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('breakfast', instance.breakfast);
  writeNotNull('lunch', instance.lunch);
  writeNotNull('snacks', instance.snacks);
  writeNotNull('dinner', instance.dinner);
  writeNotNull('posted_by_name', instance.postedByName);
  writeNotNull('created_at', instance.createdAt?.toIso8601String());
  return val;
}

_$MessOffImpl _$$MessOffImplFromJson(Map<String, dynamic> json) =>
    _$MessOffImpl(
      id: json['id'] as String,
      studentId: json['student_id'] as String,
      fromDate: DateTime.parse(json['from_date'] as String),
      toDate: DateTime.parse(json['to_date'] as String),
      reason: json['reason'] as String?,
      isApproved: json['is_approved'] as bool? ?? false,
      isAutoGenerated: json['is_auto_generated'] as bool?,
      createdAt: json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
    );

Map<String, dynamic> _$$MessOffImplToJson(_$MessOffImpl instance) {
  final val = <String, dynamic>{
    'id': instance.id,
    'student_id': instance.studentId,
    'from_date': instance.fromDate.toIso8601String(),
    'to_date': instance.toDate.toIso8601String(),
  };

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('reason', instance.reason);
  val['is_approved'] = instance.isApproved;
  writeNotNull('is_auto_generated', instance.isAutoGenerated);
  writeNotNull('created_at', instance.createdAt?.toIso8601String());
  return val;
}
